# Generated by Django 2.2.5 on 2019-09-14 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='None', help_text='Unique code, only specified characters are allowed', max_length=50, unique=True)),
                ('name', models.CharField(default='None', help_text='Name, most characters are allowed', max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('created_by', models.CharField(default='INIT', editable=False, max_length=50)),
                ('updated_by', models.CharField(default='INIT', editable=False, max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('location', models.TextField(default='TBD', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='None', help_text='Unique code, only specified characters are allowed', max_length=50, unique=True)),
                ('name', models.CharField(default='None', help_text='Name, most characters are allowed', max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('created_by', models.CharField(default='INIT', editable=False, max_length=50)),
                ('updated_by', models.CharField(default='INIT', editable=False, max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('location', models.TextField(default='TBD', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='None', help_text='Unique code, only specified characters are allowed', max_length=50, unique=True)),
                ('name', models.CharField(default='None', help_text='Name, most characters are allowed', max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('created_by', models.CharField(default='INIT', editable=False, max_length=50)),
                ('updated_by', models.CharField(default='INIT', editable=False, max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('location', models.TextField(default='TBD', max_length=100)),
                ('factory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesfactory.Factory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='None', help_text='Unique code, only specified characters are allowed', max_length=50, unique=True)),
                ('name', models.CharField(default='None', help_text='Name, most characters are allowed', max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('created_by', models.CharField(default='INIT', editable=False, max_length=50)),
                ('updated_by', models.CharField(default='INIT', editable=False, max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('location', models.TextField(default='TBD', max_length=100)),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesfactory.Line')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='line',
            name='workshop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesfactory.Workshop'),
        ),
    ]
