# Generated by Django 2.2.5 on 2019-09-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesfactory', '0002_auto_20190915_0041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='station',
            table='station',
        ),
    ]
