# Generated by Django 2.2.5 on 2019-09-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesfactory', '0004_auto_20190915_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='workshop_id',
            new_name='workshop',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='line_id',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='factory_id',
            new_name='factory',
        ),
    ]
