# Generated by Django 2.2.5 on 2019-09-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesfactory', '0006_auto_20190916_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name_plural': 'Factories'},
        ),
        migrations.AlterField(
            model_name='factory',
            name='created_by',
            field=models.CharField(default='auth.User', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='factory',
            name='description',
            field=models.TextField(default='None', help_text='Use short sentence to discribe your object', max_length=512),
        ),
        migrations.AlterField(
            model_name='factory',
            name='updated_by',
            field=models.CharField(default='auth.User', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='line',
            name='created_by',
            field=models.CharField(default='auth.User', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='line',
            name='description',
            field=models.TextField(default='None', help_text='Use short sentence to discribe your object', max_length=512),
        ),
        migrations.AlterField(
            model_name='line',
            name='updated_by',
            field=models.CharField(default='auth.User', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='created_by',
            field=models.CharField(default='auth.User', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.TextField(default='None', help_text='Use short sentence to discribe your object', max_length=512),
        ),
        migrations.AlterField(
            model_name='station',
            name='updated_by',
            field=models.CharField(default='auth.User', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='created_by',
            field=models.CharField(default='auth.User', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(default='None', help_text='Use short sentence to discribe your object', max_length=512),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='updated_by',
            field=models.CharField(default='auth.User', editable=False, max_length=50),
        ),
        migrations.CreateModel(
            name='WorkshopAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('attr_name', models.CharField(choices=[('MANAGER', 'Managers Name'), ('PHONE_NUMBER', 'Contact Phone Number')], max_length=100)),
                ('attr_value', models.CharField(max_length=100)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesfactory.Workshop')),
            ],
            options={
                'db_table': 'workshop_attr',
            },
        ),
        migrations.CreateModel(
            name='StationAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('attr_name', models.CharField(choices=[('DANGEROUS', 'Dangrous(Y/N)'), ('AUTOMATE', 'Automate(Y/N)'), ('ROBOT', 'Robot(Y/N)')], max_length=100)),
                ('attr_value', models.CharField(max_length=100)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesfactory.Station')),
            ],
            options={
                'db_table': 'station_attr',
            },
        ),
        migrations.CreateModel(
            name='LineAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('attr_name', models.CharField(choices=[('LEADER', 'Leaders Name'), ('PHONE_NUMBER', 'Contact Phone Number')], max_length=100)),
                ('attr_value', models.CharField(max_length=100)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesfactory.Line')),
            ],
            options={
                'db_table': 'line_attr',
            },
        ),
        migrations.CreateModel(
            name='FactoryAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('attr_name', models.CharField(choices=[('PLANT_CODE', 'Plant code(2 digits)'), ('NATION', 'Nation'), ('MANAGER', 'Managers Name'), ('PHONE_NUMBER', 'Contact Phone Number')], max_length=100)),
                ('attr_value', models.CharField(max_length=100)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesfactory.Factory')),
            ],
            options={
                'db_table': 'factory_attr',
            },
        ),
    ]
