# Generated by Django 2.2.5 on 2019-09-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesfactory', '0007_auto_20190917_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factoryattr',
            options={'verbose_name_plural': 'Extended attributes'},
        ),
        migrations.AlterModelOptions(
            name='lineattr',
            options={'verbose_name_plural': 'Extended attributes'},
        ),
        migrations.AlterModelOptions(
            name='stationattr',
            options={'verbose_name_plural': 'Extended attributes'},
        ),
        migrations.AlterModelOptions(
            name='workshopattr',
            options={'verbose_name_plural': 'Extended attributes'},
        ),
        migrations.AlterField(
            model_name='factory',
            name='location',
            field=models.TextField(default='TBD', help_text='Position of the location, e.g. coordinates', max_length=100),
        ),
        migrations.AlterField(
            model_name='factoryattr',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesfactory.Factory'),
        ),
        migrations.AlterField(
            model_name='line',
            name='location',
            field=models.TextField(default='TBD', help_text='Position of the location, e.g. coordinates', max_length=100),
        ),
        migrations.AlterField(
            model_name='lineattr',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesfactory.Line'),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.TextField(default='TBD', help_text='Position of the location, e.g. coordinates', max_length=100),
        ),
        migrations.AlterField(
            model_name='stationattr',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesfactory.Station'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.TextField(default='TBD', help_text='Position of the location, e.g. coordinates', max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopattr',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesfactory.Workshop'),
        ),
        migrations.AddConstraint(
            model_name='factoryattr',
            constraint=models.UniqueConstraint(fields=('factory', 'attr_name'), name='uniq_factory_attr'),
        ),
        migrations.AddConstraint(
            model_name='lineattr',
            constraint=models.UniqueConstraint(fields=('line', 'attr_name'), name='uniq_line_attr'),
        ),
        migrations.AddConstraint(
            model_name='stationattr',
            constraint=models.UniqueConstraint(fields=('station', 'attr_name'), name='uniq_station_attr'),
        ),
        migrations.AddConstraint(
            model_name='workshopattr',
            constraint=models.UniqueConstraint(fields=('workshop', 'attr_name'), name='uniq_workshop_attr'),
        ),
    ]
