# Generated by Django 2.2.5 on 2019-09-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(default='auth.User', editable=False, max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='product.Material')),
            ],
            options={
                'verbose_name_plural': 'Product from special material',
                'db_table': 'product',
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PRODUCT', 'Product'), ('FIXTURE', 'Fixture'), ('EQUIPMENT', 'Equipment')], default='NORMAL', help_text='Type of the material, product and normal is different', max_length=20),
        ),
    ]
