# Generated by Django 2.2.5 on 2019-09-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190924_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomtemplate',
            name='material',
            field=models.ForeignKey(default=-1, help_text='Ref to material', on_delete=django.db.models.deletion.PROTECT, to='product.Material'),
        ),
        migrations.DeleteModel(
            name='ProductBOM',
        ),
    ]
