# Generated by Django 2.2.5 on 2019-09-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190924_2342'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bomtemplateline',
            constraint=models.UniqueConstraint(fields=('bom_template', 'material'), name='uniq_bom_template_line'),
        ),
    ]
