# Generated by Django 2.2.5 on 2019-09-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190924_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomtemplateline',
            options={'verbose_name_plural': 'BOM template line'},
        ),
        migrations.AlterField(
            model_name='bomtemplate',
            name='revision',
            field=models.CharField(default='0', help_text='Revision number of the BOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='bomtemplate',
            name='status',
            field=models.SmallIntegerField(choices=[('100', 'CREATE'), ('200', 'RELEASE'), ('300', 'DRAFT'), ('400', 'EXPIRED')], default=100, help_text='Status,very important for maintenance'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.SmallIntegerField(choices=[('100', 'CREATE'), ('200', 'RELEASE'), ('300', 'DRAFT'), ('400', 'EXPIRED')], default=100, help_text='Status'),
        ),
    ]
