# Generated by Django 2.2.5 on 2019-09-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190924_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomtemplate',
            name='material',
        ),
        migrations.AddField(
            model_name='material',
            name='bom_template_code',
            field=models.ForeignKey(default='NONE', help_text='Link to BOM template', on_delete=django.db.models.deletion.PROTECT, to='product.BomTemplate', to_field='code'),
        ),
    ]
