# Generated by Django 2.2.5 on 2019-09-24 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190925_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='bom_template_code',
            field=models.ForeignKey(db_column='bom_template_code', db_constraint=False, default='NONE', help_text='Link to BOM template', on_delete=django.db.models.deletion.PROTECT, to='product.BomTemplate', to_field='code'),
        ),
    ]
