# Generated by Django 2.2.5 on 2019-09-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190925_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='bom_template_code',
        ),
        migrations.AddField(
            model_name='material',
            name='bom_template',
            field=models.ForeignKey(db_constraint=False, default=-1, help_text='Link to BOM template', on_delete=django.db.models.deletion.PROTECT, to='product.BomTemplate', to_field='code'),
        ),
    ]
